### ISSUE TITLE
Create Starter Codes

### ISSUE THREAD

**Issue by JoanneWooW** [DevOps-Agile-Squad/orders#14]
**As a** Developer
**I need** two starter codes called ``models.py`` and ``routes.py`` in our repo
**So that** we can have starter codes to add features in it

**Assumptions:** 

* ``models.py`` should hold our model definitions of orders 
* ``routes.py`` should contain our Flask service routes
* A good starter template: https://github.com/nyu-devops/project-template

**Acceptance Criteria:**

```
When we clone from our repo
Then we should get a folder with models.py and routes.py in it
```

**Comment by luke0zong** [comment]
A good starter template: https://github.com/nyu-devops/project-template
