### ISSUE TITLE
Add order API call to return items in a specific order

### ISSUE THREAD

**Issue by OliverZWang** [DevOps-Agile-Squad/orders#2]
**As a** user
**I need** a way to see all the items in an order
**So that** I can easily look up what I have ordered in the past

**Assumptions:** 
* Add an URL of `/orders/{id}/items`
* The program should retrieve all the items and their quantities in the specified order. 
* URL should return a list of JSON objects that represent the items in this order and their corresponding quantities. 

**Acceptance Criteria:**
```
Given the ID 'x' is a valid order ID
When the endpoint '/orders/x/itmes' is called
Then the program should return a list of all the items and their quantities in order 'x' in JSON format
```

**Comment by JoanneWooW** [comment]
Hey guys, everything this story needs has been already in the template. I didn't change anything. So no pull request here.
