### ISSUE TITLE
Construct CI pipeline to run tests for every push to Main and every PR

### ISSUE THREAD

**Issue by OliverZWang** [DevOps-Agile-Squad/orders#36]
**As a** developer
**I need** tests to run automatically for every push to the main branch and every PR
**So that** it is easy to make sure the main branch is always deployable. 

**Assumptions:** 
* Run TDD test cases first
* Then run BDD test cases
* Finally report the code coverage

**Acceptance Criteria:**
```
Given the code that a developer is trying to merge to the main branch create a PR for includes tests
When the developer merge the code into the main branch or submit a PR
Then the automatic tests would run via Travis CI
```

**Comment by luke0zong** [comment]
Reopened to add BDD test jobs.
