### ISSUE TITLE
Update the Vagrantfile to download and install the IBM Cloud CLI

### ISSUE THREAD

**Issue by OliverZWang** [DevOps-Agile-Squad/orders#39]
**As a** developer
**I need** IBM Cloud CLI to be installed on my virtual machine
**So that** I can interact with IBM Cloud via command line in my dev environment

**Assumptions:** 
* We use a Vagrantfile to build and run VMs

**Acceptance Criteria:**
```
Given an updated Vagrantfile
When the VM is built and spun up using the Vagrantfile
Then IBM Cloud CLI should be installed on the VM
```

**Comment by luke0zong** [comment]
Refer https://github.com/nyu-devops/lab-bluemix-cf/blob/master/Vagrantfile
