### ISSUE TITLE
Adding an item to an order should  send back a location header of the newly created item with the 201return code.

### ISSUE THREAD

**Issue by nbhagat3136** [DevOps-Agile-Squad/orders#42]
As a developer
I need adding an item to an order should send back a location header of the newly created item with the 201 created  return code.
So that appropriate test for add item to order can be implemented.

Assumptions:
Adding item to order done successfully.

Acceptance Criteria
Given the item is added to order 
When the item post is successful
Then 201 return code is generated.

**Comment by JoanneWooW** [comment]
Hi, thanks for creating this issue. But please use correct markdown and give a detailed Acceptance Criteria instead of saying `None`. Thank you!
