### ISSUE TITLE
Create a simple single page UI

### ISSUE THREAD

**Issue by luke0zong** [DevOps-Agile-Squad/orders#44]
**As a** Customer
**I need** A web UI to access my orders
**So that** I can view, search, and interact with my orders

**Assumptions:** 
* Default page list the orders
* Support simple search functions
* Has a button to cancel an order

**Acceptance Criteria:**
```
When the customer interacts with the web UI
Then the REST APIs are performed accordingly
```

**Comment by pkutlesa** [comment]
Sample UI: https://github.com/nyu-devops/lab-flask-bdd
