### ISSUE TITLE
BDD Scenario for Read an Order

### ISSUE THREAD

**Issue by JoanneWooW** [DevOps-Agile-Squad/orders#48]
**As a** Developer  
**I need** a way to test the behavior of my website  
**So that** I can know it works well  

**Assumptions:** 
* None for now

**Acceptance Criteria:**
```
Given the application is running
When you run behave command
Then the corresponding scenario tests should pass

// The behavior we need is listed below
When I visit the "Home Page"
And I input the data for "Order ID"
And I click the "Retrieve" button
Then I should see the order in the results
```

**Comment by nbhagat3136** [comment]
Please update the Assumptions and Acceptance criteria of this user story. Thank you.

**Comment by JoanneWooW** [comment]
@nbhagat3136 Thank you for pointing out! I will update incomplete stories as soon as possible (hopefully tonight).

**Comment by nbhagat3136** [comment]
Hi . Thanks. I edited the story little bit. It has to capture Order ID and Item ID.
