### ISSUE TITLE
Add the ability to create an order

### ISSUE THREAD

**Issue by nbhagat3136** [DevOps-Agile-Squad/orders#5]
**As a**  user 
**I need**  a way to create a order with items and quantity
**So that**   order is created

**Assumptions:** 
* Add an URL of /orders/{id}
* The program should create all the items and quantity that is posted
* URL should return  JSON objects that represent the items and quantity posted in the order

**Acceptance Criteria:**
```
Given  Order is created with id 
When endpoint order post is called
Then the order to be created in JSON Format
```

**Comment by OliverZWang** [comment]
Please update this user story to delete the `...` and use the correct Markdown syntax for bullet points. Thank you : )
