### ISSUE TITLE
BDD Scenario for delete feature

### ISSUE THREAD

**Issue by nbhagat3136** [DevOps-Agile-Squad/orders#51]
As a developer
I need to write  behavior tests for delete functionality
So that I can ensure delete feature works as intended

**Assumptions:** 
UI is created

**Acceptance Criteria:**
All the tests should pass
Given Order 'x' exists
When I visit the "Home Page"
 And I set the "Order" to "x"
 And I press the "Delete" button
 Then I should see "Order Deleted Successfully!" in the results
 And I should not see "x" in the results

**Comment by nbhagat3136** [comment]
Please assign it to yourself while working. Thank you.

**Comment by OliverZWang** [comment]
I added the assignee (assuming it's @pkutlesa since he moved the card) so that we comply with the requirements. Happy to help or take this one if needed : )

**Comment by pkutlesa** [comment]
Thanks for the reminder, assigning me, and offering to help. I will reach out if needed :)

**Comment by pkutlesa** [comment]
Hey, @OliverZWang I would like to follow up on your offer to assist with this issue :) 
Please let me know if you would be interested in a peer programming session so that I can share with you my current progress and discuss considerations I have moving forward.

**Comment by OliverZWang** [comment]
> Hey, @OliverZWang I would like to follow up on your offer to assist with this issue :)
> Please let me know if you would be interested in a peer programming session.

Oh yeah I'd be happy to. Will DM on slack : )

**Comment by nbhagat3136** [comment]
Hey guys! Looks like I missed the message .. I would like to follow along in case there is any peer programming session planned  later in day.
