### ISSUE TITLE
Refactor using Flask-RESTX

### ISSUE THREAD

**Issue by JoanneWooW** [DevOps-Agile-Squad/orders#53]
**As a** Developer  
**I need** to move from a basic Flask application to one that uses Flask- RESTX
**So that** we can provide Swagger documentation easily

**Assumptions:** 
* Refactor micro service to use Flask-RESTX following the file layout outlined in lab-flask-restplus-swagger.
* Make sure that all HTTP errors return json error messages and not html.

**Acceptance Criteria:**
```
Given the code have been moved into the new framework
When run test cases
Then the implementation still works like the original
```

**Comment by pkutlesa** [comment]
https://github.com/nyu-devops/lab-flask-restplus-swagger
