### ISSUE TITLE
Set up the CI/CD DevOps Pipeline 

### ISSUE THREAD

**Issue by pkutlesa** [DevOps-Agile-Squad/orders#58]
**As a** developer 
**I need** to set up a DevOps pipeline 
**So that** me and other developers can start developing each stage of the pipeline 

**Assumptions:** 
* The pipeline consists of 4 stages: Build, Dev, Test, Prod 
* The pipeline is set up in the IBM cloud

**Acceptance Criteria:**
```
Given that all developers have access to the IBM Cloud 
When I set up the DevOps pipeline 
Then other developers can begin to work on each stage of the pipeline 
```

**Comment by luke0zong** [comment]
I confirm that I can access the toolchain.
