### ISSUE TITLE
Connect DevOps pipeline to GitHub repository 

### ISSUE THREAD

**Issue by pkutlesa** [DevOps-Agile-Squad/orders#59]
**As a** developer 
**I need** to connect the DevOps pipeline to our GitHub repository 
**So that** changes to the master branch automatically trigger the pipeline

**Assumptions:** 
* Connect the DevOps pipeline to the GitHub repository via a webhook 

**Acceptance Criteria:**
```
Given a working DevOps pipeline
When it is connected to the GitHub repository 
Then changes to the master branch automatically initiate an iteration through the pipeline (build, test, deploy)  
```

**Comment by JoanneWooW** [comment]
Note: this story can only be done by the owner of the org in GitHub (which is Philip).
