### ISSUE TITLE
Add the ability to update a order

### ISSUE THREAD

**Issue by nbhagat3136** [DevOps-Agile-Squad/orders#6]
**As a**   user 
**I need**   a way to update my order
**So that**  order is updated

**Assumptions:** 
* Add an URL of /orders/{id}
* The program should update  the items and quantity that is posted
* URL should return JSON objects that represent the updated items and quantity posted in the order

**Acceptance Criteria:**
```
Given  order would be updated for the item id x.
When the endpoint update is called
Then The order is updated in JSON Format
```

**Comment by OliverZWang** [comment]
Please update this user story to delete the `...` and use the correct Markdown syntax for bullet points. Thank you : )
