### ISSUE TITLE
Add a Unit Test Job to the Build Stage of the DevOps Pipeline 

### ISSUE THREAD

**Issue by pkutlesa** [DevOps-Agile-Squad/orders#60]
**As a** developer  
**I need** unit tests to run during the Build stage of the pipeline   
**So that** I can ensure individual functionalities are working correctly before deployment to Dev space  

**Assumptions:** 
* Run unit tests with nosetests 

**Acceptance Criteria:**
```
Given working unit tests
When I add a unit test job to the Build stage 
Then unit tests automatically run before deployment to Dev space 
```

**Comment by JoanneWooW** [comment]
It's already been done when I try to accomplish this story. So no PR.
